### PR TITLE
Adding .pcap extension.

### PR DESCRIPTION
**Pull request by renaudholcombe**
Howdy, I created this PR to add the .pcap extension to the pcap files being created. I made this modification since an automated processor I use only recognizes files with that extension and it makes sense to me to have the files use that convention rather than just the identifier currently being used. 

No sweat if you don't think it's a good idea; I created the PR more as a suggestion than anything else. If you think it would better as an added parameter to the application, I can also do that.

Thanks!

### CODE REVIEW

**Comment by renaudholcombe** [comment]
Closing as I've got a few more changes in the hopper and it doesn't look like PRs are getting merged.

**Comment by vrtadmin** [comment]
Well, I was going to merge it ;). But I'll wait on your other stuff!

**Comment by renaudholcombe** [comment]
Doh! Sorry about that @vrtadmin, I didn't realize this was still active given the other open pull requests from 2016. Let me reopen this; seems I was a little quick on the draw.

Thanks!

**Comment by vrtadmin** [comment]
Thanks for that.  Not a problem.  Yes. This is an easy change, I need to get @mroesch-csco to review the others.

**Pull request merged**
